server:
  port: 8080

spring:
  application:
    name: main-service
  datasource:
    url: jdbc:postgresql://localhost:5433/main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never

stats:
  server:
    url: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.practicum.mainservice: DEBUG
    org.springframework.web: DEBUG
