server:
  port: 8080
  tomcat:
    max-http-post-size: 10MB
  max-http-header-size: 8192

spring:
  application:
    name: main-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/main_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.sql.init: DEBUG

stats:
  server:
    url: ${STATS_SERVER_URL:http://localhost:9090}
