name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build project
      run: mvn clean install -DskipTests
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and start services
      run: |
        export SPRING_PROFILES_ACTIVE=ci
        docker-compose build
        docker-compose up -d
    
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start..."
        sleep 45
        
        # Проверяем логи для диагностики
        echo "=== Main Service Logs ==="
        docker-compose logs main-service | tail -10
        
        # Проверяем доступность сервисов
        echo "Checking main service..."
        timeout 120 bash -c 'until curl -f http://localhost:8081/categories 2>/dev/null; do echo "Waiting..."; sleep 5; done'
        
        echo "Checking stats service..."
        timeout 120 bash -c 'until curl -f "http://localhost:9090/stats?start=2024-01-01T00:00:00&end=2024-12-31T23:59:59" 2>/dev/null; do echo "Waiting..."; sleep 5; done'
    
    - name: Run integration tests
      run: |
        # Тестируем основные эндпоинты
        echo "Testing main service endpoints..."
        
        # Тест главной страницы
        curl -f http://localhost:8081/ || exit 1
        
        # Тест создания категории
        curl -X POST http://localhost:8081/admin/categories \
          -H "Content-Type: application/json" \
          -d '{"name": "Test Category"}' || exit 1
        
        # Тест получения категорий
        curl -f http://localhost:8081/categories || exit 1
        
        echo "Testing stats service endpoints..."
        
        # Тест получения статистики (проверяем что сервис отвечает)
        curl -f "http://localhost:9090/stats?start=2024-01-01T00:00:00&end=2024-12-31T23:59:59" || exit 1
        
        # Проверяем health endpoint stats-service
        curl -f http://localhost:9090/actuator/health || exit 1
        
        echo "All integration tests passed!"
    
    - name: Stop services
      if: always()
      run: docker-compose down
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: service-logs
        path: |
          docker-compose.logs
        retention-days: 7
